### ISSUE TITLE
Can --add-file and --add-folder be merged?

### ISSUE THREAD

**Issue by apjanke** [andreyvit/create-dmg#84]
Do `--add-file` and `--add-folder` really need to be separate options? Couldn't `--add-file` take either regular files or folders as its argument?

For example: https://github.com/octave-app/create-dmg/commit/ccdaeca5010303f65bd8061eef11ac8a8f642375.

**Comment by aonez** [comment]
You're right, those should be merged into one. In fact, the current code is the same for booth file and folder, since they use `-a` that basically is `-dR`.

So probably just removing the folder steps and changing the files description will do.

Keeping the `--add-folder` argument (even if it uses `ADD_FILE_TARGETS`) could be good for not breaking current user scripts.

**Comment by apjanke** [comment]
Yeah, let's make it a hidden, undocumented option for back-compatibility. I'll make a PR.

**Comment by apjanke** [comment]
#88
